
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqluimnbylemnwezujuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbHVpbW5ieWxlbW53ZXp1anVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTI4NTAsImV4cCI6MjA1ODQ4ODg1MH0.VshszV6M8BhFDMZW14fitHhMlc3-l0CY7aj1UE7Tl5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
